<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Wfx.Cli/Wfx.Cli.csproj" AdditionalProperties="SelfContained=false" />
  </ItemGroup>
</Project>
