<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>wfx</AssemblyName>
    <RootNamespace>Wfx.Cli</RootNamespace>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <StripSymbols>true</StripSymbols>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Wfx.Cli.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Wfx.Core/Wfx.Core.csproj" />
    <ProjectReference Include="../Wfx.PowerShell/Wfx.PowerShell.csproj" />
    <ProjectReference Include="../Wfx.Providers/Wfx.Providers.csproj" />
    <ProjectReference Include="../Wfx.Tools/Wfx.Tools.csproj" />
    <ProjectReference Include="..\Wfx.Mcp\Wfx.Mcp.csproj" />
  </ItemGroup>
</Project>
